FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

COPY ./*Backend.csproj ./ 
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app/out

# Etapa de producción
FROM mcr.microsoft.com/dotnet/aspnet:7.0

WORKDIR /app

COPY --from=build /app/out ./

EXPOSE 80

ENTRYPOINT ["dotnet", "Backend.dll"]